# Bellatrix lite configuration
{
    core: {
        reset_address: 0x80000000,
    },
    trigger: {
        enable: False
    },
    isa: {
        enable_rv32m: True,
        enable_extra_csr: True,
        enable_user_mode: False,
    },
    predictor: {
        enable: False
    },
    icache: {
        enable: False
    }
}
